### ISSUE TITLE
on the parity_ooberror_vs_sigma_n100_d1000_ntress1000

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#1]
why does error _decrease_ with increasing variance?
what i would have expected is error to _increase_ with increasing variance, as it does for the d << n cases....

**Comment by tyler-tomita** [comment]
I haven't figured this out yet. The fact that it only happens for the TF+meandiff classifier means that it's something specific to the concatenation of the mean difference vectors. The rest of the code is identical. The mean difference vectors are doing a lot of unexpected things. Theoretically, for the XOR data the mean difference vector in the binary classification case should approach all zeros as n gets large. So, for n >> d, I would suspect that TF+meandiff wouldn't improve upon TF+. However, I've only done the n << d case. I'm wondering if what we are seeing is a phenomenon that's happening because the mean difference vectors are being poorly estimated when n << d? Not sure, just throwing thoughts out there

**Comment by jovo** [comment]
unclear.
worth investigation the other case probably...
