### ISSUE TITLE
xor_#trees_to_stabilize

### ISSUE THREAD

**Issue by jovo** [ttomita/RandomerForest#5]
so cool that #trees to stabilize is better for us than RF.
this means that we could be more efficient even too?
is that true?
can you make a scatter plot: walltime vs. performance, for the 4 diff algs, on XOR while varying something (either n or d or sigma)?

**Comment by tyler-tomita** [comment]
yep. one thing i was unsure of was what to use as the criteria for determining the point at which the algorithm has stabilized. I computed the point at which stabilization occurred as the point at which the variance of Lhat over the last 20 trees was zero. 20 trees was chosen because it empirically seemed reasonable

**Comment by jovo** [comment]
no need for a threshold. 
lets just plot variance of LHat across trees vs #trees. the reader will be able to assess for themselves.
